# Generated by Django 3.2.20 on 2025-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(default='No overview available.')),
                ('poster_path', models.CharField(max_length=255)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
